# Generated by Django 5.1.1 on 2024-10-06 18:20

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0002_remove_file_is_enabled'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='product',
            name='is_enabled',
        ),
    ]
