# Generated by Django 5.1.1 on 2024-10-06 18:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0003_remove_product_is_enabled'),
    ]

    operations = [
        migrations.AddField(
            model_name='file',
            name='is_enabled',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='product',
            name='is_enabled',
            field=models.BooleanField(default=True),
        ),
    ]
