# Generated by Django 5.1.1 on 2024-10-06 18:34

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0004_file_is_enabled_product_is_enabled'),
    ]

    operations = [
        migrations.RenameField(
            model_name='product',
            old_name='category',
            new_name='categories',
        ),
    ]
